package co.aartea.to_dolist;

import android.content.Intent;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    //Variable assignment

    String getString;

    ListView lv;
    TextView tv;
    EditText et;
    ArrayList<String> lists;             //Create an array that will hold array lists
    ArrayAdapter<String> adapter;        //To port over info. from ArrayList to ListView

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //Instantiate, initialize
        lv = (ListView) findViewById(R.id.listView);
        tv = (TextView) findViewById(R.id.tv);
        et = (EditText) findViewById(R.id.et);
        lists = new ArrayList<>();
        adapter = new ArrayAdapter<>
                (MainActivity.this,android.R.layout.simple_list_item_1, lists);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        //Set adapter
        lv.setAdapter(adapter);
        lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent i = new Intent(MainActivity.this,sub_list.class);
                i.putExtra("main_list",lists.get(position));
                startActivity(i);
            }
        });

        //Action button will handle add request; perhaps edittext within listview
        //Will need to find a way to add an item to the array...
        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        assert fab != null;
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                    getString = et.getText().toString();
                    lists.add(getString);
                    adapter.notifyDataSetChanged();
                    et.getText().clear();
                //if successful, add a Snackbar saying so
                //else, handle error and catch it!
                Snackbar.make(view, "Added!", Snackbar.LENGTH_SHORT)
                        .setAction("Action", null).show();
                //et.getText().clear();
                //Inserted code from outside source: will make keyboard disappear after text is entered.
                try{
                    InputMethodManager arbitraryName = (InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);
                    arbitraryName.hideSoftInputFromWindow(getCurrentFocus().getWindowToken(), 0);
                    }
                catch(Exception e){}
            }
        });
    }




    //Generated by default project settings -- will mess with later.
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
